"""Diagnostic tools for Knowledge Component (KC) training."""

import math
import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

import torch

from train.types import (
    KCDiagnosticFamilyStats,
    KCDiagnosticReport,
)

# Pylint suppressions for diagnostic complexity
# pylint: disable=too-many-positional-arguments,too-many-locals,unused-argument,too-many-return-statements

# --- Types ---


# --- Canonical Gathering ---


# --- Existing Statistic Classes ---


@dataclass
class FamilyStats:
    """Accumulator for per-family statistics."""

    # Target Rate
    num_pos: int = 0
    num_total_labels: int = 0

    # Target Cardinality (positives per example)
    card_reservoir: List[int] = field(default_factory=list)
    num_examples: int = 0
    num_empty: int = 0

    # Loss
    sum_nll: float = 0.0
    count_nll: int = 0

    # Predictions (New)
    sum_prob_pos: float = 0.0
    count_prob_pos: int = 0
    sum_prob_neg: float = 0.0
    count_prob_neg: int = 0
    fp_count: int = 0
    fn_count: int = 0

    # Extended Separation Metrics
    sum_logit_pos: float = 0.0
    count_logit_pos: int = 0
    sum_logit_neg: float = 0.0
    count_logit_neg: int = 0

    # Recall Counters (TPs at thresholds)
    tp_01_count: int = 0  # pred >= 0.1
    tp_05_count: int = 0  # pred >= 0.5

    # Collisions / Uniqueness
    unique_ids: Set[int] = field(default_factory=set)
    unique_capped: bool = False
    max_unique_cap: int = (
        100_000  # Reduced from 2M - only need sample for collision detection
    )
    precomputed_unique_count: Optional[int] = (
        None  # Set from label phase for amortized tracking
    )

    # Masking (specific to reading_gram)
    mask_count: int = 0
    total_token_count: int = 0

    def add_cardinality(self, count: int) -> None:
        self.num_examples += 1
        if count == 0:
            self.num_empty += 1

        # Reservoir sampling for p50/p90
        if len(self.card_reservoir) < 4096:
            self.card_reservoir.append(count)
        else:
            j = random.randint(0, self.num_examples - 1)
            if j < 4096:
                self.card_reservoir[j] = count

    def add_unique_ids(self, ids: List[int]) -> None:
        if not self.unique_capped:
            self.unique_ids.update(ids)
            if len(self.unique_ids) > self.max_unique_cap:
                self.unique_capped = True
                self.unique_ids.clear()  # Free memory


class KCEpochDiag:
    """Accumulates and reports per-epoch KC diagnostics."""

    def __init__(self) -> None:
        self.families: Dict[str, FamilyStats] = {}
        # We need a stable hash capability if we want to report collisions on hashed values,
        # but the inputs to update are typically already hashed or raw IDs.
        # We assume 'pos_ids' passed to update are the relevant IDs for collision checking.

    def load_precomputed_unique_counts(self, dataset_dir: str) -> None:
        """Load precomputed KC unique ID counts from the label phase.

        This skips the expensive live collision tracking during training.
        The counts file is generated by scripts/label.py Phase 2/3.
        """
        import json
        import os

        counts_path = os.path.join(dataset_dir, "kc_unique_counts.json")
        if not os.path.exists(counts_path):
            return  # No precomputed counts, will use live tracking

        with open(counts_path, "r", encoding="utf-8") as f:
            counts = json.load(f)

        # Pre-populate families with precomputed counts
        for family_name, count in counts.items():
            if family_name not in self.families:
                self.families[family_name] = FamilyStats()
            self.families[family_name].precomputed_unique_count = count

    def update_family(
        self,
        family_name: str,
        pos_ids: torch.Tensor,  # (B, P) or list of lists, flattened logic preferred
        pos_mask: torch.Tensor,  # (B, P) bool
        probs: torch.Tensor,  # (B, P_sample)
        targets: torch.Tensor,  # (B, P_sample) 0 or 1
        nll: float,
        mask_id: Optional[int] = None,  # For reading_gram masking check
        logits: Optional[torch.Tensor] = None,
    ) -> None:
        if family_name not in self.families:
            self.families[family_name] = FamilyStats()
        stats = self.families[family_name]

        # A4: Validate shapes
        if pos_ids.dim() != 2:
            raise ValueError(
                f"pos_ids must be 2D, got {pos_ids.shape} (family={family_name})"
            )

        if not pos_ids.shape == pos_mask.shape == probs.shape == targets.shape:
            raise ValueError(
                f"Shape mismatch in update_family({family_name}): "
                f"ids={pos_ids.shape} mask={pos_mask.shape} "
                f"probs={probs.shape} targets={targets.shape}"
            )

        # 1. Target Rate & Cardinality
        batch_size = pos_mask.size(0)

        # Count positives per example (stays on GPU, just get int counts)
        pos_counts = pos_mask.sum(dim=1)
        total_pos = int(pos_counts.sum().item())
        stats.num_pos += total_pos

        # Cardinality tracking - convert counts to CPU once
        counts_list = pos_counts.cpu().tolist()
        for c in counts_list:
            stats.add_cardinality(c)

        stats.num_total_labels += int(targets.numel())

        # 2. Collisions (Track usage of IDs) - OPTIMIZED
        # Only compute valid_pos_ids_cached if we need it for:
        # - Unique ID tracking (when no precomputed counts)
        # - Masking (when mask_id is provided, i.e., reading_gram family)
        valid_pos_ids_cached = None
        needs_unique_tracking = (
            not stats.unique_capped and stats.precomputed_unique_count is None
        )
        needs_masking = mask_id is not None

        if total_pos > 0 and (needs_unique_tracking or needs_masking):
            # Only compute once for both uses if needed
            valid_pos_ids_cached = pos_ids[pos_mask].detach()

            # Unique ID sampling (only if not precomputed)
            if needs_unique_tracking:
                sample_size = min(1000, valid_pos_ids_cached.numel())
                if sample_size < valid_pos_ids_cached.numel():
                    # Random sample indices - only if needed
                    indices = torch.randperm(
                        valid_pos_ids_cached.numel(), device=valid_pos_ids_cached.device
                    )[:sample_size]
                    sampled_ids = valid_pos_ids_cached[indices].cpu().tolist()
                else:
                    sampled_ids = valid_pos_ids_cached.cpu().tolist()
                stats.add_unique_ids(sampled_ids)

        # 3. Predictions - OPTIMIZED: avoid indexed tensor creation
        # Use multiplication with float targets instead of boolean indexing
        p_detach = probs.detach()
        targets_float = targets.float()

        # pos_indices and neg_indices as float masks (0.0 or 1.0)
        pos_mask_float = targets_float
        neg_mask_float = 1.0 - targets_float

        # OPTIMIZED: Compute sums directly without torch.stack to avoid allocations
        # Each sum is a scalar tensor, calling .item() extracts it
        num_pos_samples = int(targets_float.sum().item())
        num_neg_samples = int(neg_mask_float.sum().item())

        preds_float = (p_detach > 0.5).float()

        stats.sum_prob_pos += (p_detach * pos_mask_float).sum().item()
        stats.count_prob_pos += num_pos_samples
        stats.sum_prob_neg += (p_detach * neg_mask_float).sum().item()
        stats.count_prob_neg += num_neg_samples
        stats.fp_count += int((preds_float * neg_mask_float).sum().item())
        stats.fn_count += int(((1.0 - preds_float) * pos_mask_float).sum().item())
        stats.tp_01_count += int(
            ((p_detach >= 0.1).float() * pos_mask_float).sum().item()
        )
        stats.tp_05_count += int(
            ((p_detach >= 0.5).float() * pos_mask_float).sum().item()
        )

        # Logits stats
        if logits is not None:
            l_detach = logits.detach()
            stats.sum_logit_pos += (l_detach * pos_mask_float).sum().item()
            stats.count_logit_pos += num_pos_samples
            stats.sum_logit_neg += (l_detach * neg_mask_float).sum().item()
            stats.count_logit_neg += num_neg_samples

        # 4. Loss
        stats.sum_nll += nll * batch_size
        stats.count_nll += batch_size

        # 5. Masking (specific to reading_gram) - OPTIMIZED: reuse cached valid_pos_ids
        if mask_id is not None and valid_pos_ids_cached is not None:
            stats.mask_count += int((valid_pos_ids_cached == mask_id).sum().item())
            stats.total_token_count += total_pos

    def get_stats(self) -> KCDiagnosticReport:
        """Return structured statistics."""
        data: Dict[str, KCDiagnosticFamilyStats] = {}
        sorted_families = sorted(self.families.keys())

        for name in sorted_families:
            s = self.families[name]
            # Rate
            rate = s.num_pos / max(1, s.num_total_labels)

            # Cardinality
            if s.card_reservoir:
                s.card_reservoir.sort()
                n = len(s.card_reservoir)
                p50 = s.card_reservoir[n // 2]
                p90 = s.card_reservoir[int(n * 0.9)]
            else:
                p50, p90 = 0, 0

            empty_pct = s.num_empty / max(1, s.num_examples)

            # Preds
            nll = s.sum_nll / max(1, s.count_nll)
            p = max(1e-6, min(rate, 1 - 1e-6))
            bias_nll = -(rate * math.log(p) + (1 - rate) * math.log(1 - p))
            dnll = nll - bias_nll

            # Mask
            mask_pct = 0.0
            if s.total_token_count > 0:
                mask_pct = s.mask_count / s.total_token_count

            # Extended Metrics
            prob_pos_mean = s.sum_prob_pos / max(1, s.count_prob_pos)
            prob_neg_mean = s.sum_prob_neg / max(1, s.count_prob_neg)
            auc_proxy = prob_pos_mean - prob_neg_mean

            fp_rate = s.fp_count / max(1, s.count_prob_neg)
            fn_rate = s.fn_count / max(1, s.count_prob_pos)
            support = s.num_pos / max(1, s.num_examples)

            # Extended metrics
            logit_pos_mean = s.sum_logit_pos / max(1, s.count_logit_pos)
            logit_neg_mean = s.sum_logit_neg / max(1, s.count_logit_neg)
            delta_p = prob_pos_mean - prob_neg_mean

            # Recall = TP / (TP + FN) = TP / TotalPos
            # We use count_prob_pos as the denominator (positives in the sampled set)
            recall_01 = s.tp_01_count / max(1, s.count_prob_pos)
            recall_05 = s.tp_05_count / max(1, s.count_prob_pos)

            family_stats = KCDiagnosticFamilyStats(
                rate=rate,
                p50=p50,
                p90=p90,
                empty_pct=empty_pct,
                dnll=dnll,
                mask_pct=mask_pct,
                loss_mean=nll,
                prob_pos_mean=prob_pos_mean,
                prob_neg_mean=prob_neg_mean,
                auc_proxy=auc_proxy,
                fp_rate=fp_rate,
                fn_rate=fn_rate,
                support=support,
                logit_pos_mean=logit_pos_mean,
                logit_neg_mean=logit_neg_mean,
                delta_p=delta_p,
                recall_01=recall_01,
                recall_05=recall_05,
            )
            data[name] = family_stats

        return KCDiagnosticReport(families=data)


# --- Formatting ---
